# Generated by Django 5.1.6 on 2025-02-13 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_part_variant_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(choices=[('KANAT TAKIMI', 'KANAT'), ('GOVDE TAKIMI', 'GOVDE'), ('KUYRUK TAKIMI', 'KUYRUK'), ('AVIYONIK TAKIMI', 'AVIYONIK'), ('MONTAJ TAKIMI', 'MONTAJ')], max_length=50, unique=True),
        ),
    ]
